name: Code coverage via codecov

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #conf-flags: [--enable-openmp, --disable-openmp, --enable-mixed-mode]
    container:
      image: underwoo/ubuntu_libfms_gnu
      env:
        FCFLAGS: "-I/usr/include  --coverage"
        LDFLAGS: "--coverage -lm"
        CPPFLAGS: "--coverage"
        CFLAGS: "--coverage"
        VERBOSE: 1
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Prepare GNU autoconf for build
      run: autoreconf -if
    - name: Configure the build
      run: ./configure #${{ matrix.conf-flags }}
    - name: Build the library
      run: make check
    - name: Send coverage results to codecov.io
      shell: bash
      run: bash <(curl -s https://codecov.io/bash)
